title:            Craig G Wilson
description:      Personal blog about software and life.
disqus_shortname: 
#Comment out url when working locally to resolve base urls correctly
#url:              http://craiggwilson.github.io

# Owner/author information
owner:
  name:           Craig Wilson
  avatar:         avatar.jpg
  bio:            "This blog represents my thoughts.  Mostly, they will be about software development, because that is what I do.  I work for 10gen as a mongodb driver engineer and evangelist developing software and tools for other developers."
  # Social networking links used in footer. Update and remove as you like.
  twitter:        craiggwilson
  github:         craiggwilson
  stackoverflow:  http://stackoverflow.com/users/25333/craig-wilson

# Links to include in top navigation
# For external links add external: true
links:
  - title: MongoDB
    url: http://mongodb.org
    external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Chicago
future:      false
pygments:    true
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   pretty

# Amount of post to show on home page
paginate: 5

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: true

  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]